### ISSUE TITLE
infra(CD): Continuous Deployment

### ISSUE THREAD

**Issue by kimseungbin** [f-lab-edu/meet-up#10]
# Todos

- [x] Create AWS account
- [x] Create IAM user
- [x] #15
- [x] Upload a default docker image
  Without an image already saved in ECR, NAT gateway must be created and it costs!
- [x] #34
- [x] #38
- [ ] Add GitHub workflow for Cfn lint
- [x] #50
- [x] #52
- [ ] #58
