### ISSUE TITLE
chore: Implement Microservices Architecture

### ISSUE THREAD

**Issue by kimseungbin** [f-lab-edu/meet-up#14]
# Todos

- [x] Create a section in README.md
- [x] Create an app for each service.
- [x] Set SWC as builder
  [Nestjs SWC monorepo](https://docs.nestjs.com/recipes/swc#monorepo)
- [x] #17

# References

- [Nest Microservices Basics](https://docs.nestjs.com/microservices/basics)
