### ISSUE TITLE
feat: Add entities

### ISSUE THREAD

**Issue by kimseungbin** [f-lab-edu/meet-up#23]
# Todos

- [x] Generate entities library
- [x] Add member entity
- [x] Add meeting entity
- [x] Add attendance entity
- [ ] Add abstract entity to pass on date-related columns
